"use client";
import { useEffect, useState, useTransition } from "react";
import type { IndexRunSummary, RankingConfig } from "@samplehub/contracts";
const API = process.env.NEXT_PUBLIC_API_URL ?? "http://127.0.0.1:8000/v1";
export function AdminDashboard() {
  const [runs, setRuns] = useState<IndexRunSummary[]>([]); const [ranking, setRanking] = useState<RankingConfig | null>(null); const [health, setHealth] = useState<Record<string, unknown> | null>(null); const [pending, startTransition] = useTransition();
  async function refresh() { const [runsResponse, rankingResponse, healthResponse] = await Promise.all([fetch(`${API}/admin/index-runs`), fetch(`${API}/admin/ranking`), fetch(`${API}/health`)]); setRuns(await runsResponse.json()); setRanking(await rankingResponse.json()); setHealth(await healthResponse.json()); }
  useEffect(() => { void refresh(); const timer = window.setInterval(() => void refresh(), 5000); return () => window.clearInterval(timer); }, []);
  async function start(mode: "full" | "incremental") { await fetch(`${API}/admin/index-runs`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ mode }) }); await refresh(); }
  async function saveRanking() { if (!ranking) return; await fetch(`${API}/admin/ranking`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify(ranking) }); await refresh(); }
  return <div className="admin-grid"><section className="panel system-panel"><div className="panel-heading"><div><p className="kicker">SYSTEM</p><h2>Runtime health</h2></div><span className="status-dot">LOCAL</span></div><pre>{health ? JSON.stringify(health, null, 2) : "Checking services…"}</pre></section>
    <section className="panel index-panel"><div className="panel-heading"><div><p className="kicker">INDEX</p><h2>Catalog operations</h2></div><div className="button-pair"><button onClick={() => startTransition(() => void start("incremental"))}>Incremental</button><button className="primary" onClick={() => startTransition(() => void start("full"))}>Full rebuild</button></div></div>
      <div className="run-list">{runs.length ? runs.slice(0, 6).map((run) => <div className="run" key={run.id}><span className={`run-state ${run.status}`}>{run.status}</span><div><strong>{run.mode} index</strong><small>{run.processedProducts.toLocaleString()} / {run.totalProducts.toLocaleString()} products · {run.captionedImages.toLocaleString()} captions · {run.cachedCaptions.toLocaleString()} cached · {run.failedImages} image / {run.failedCaptions} caption failures</small></div><progress value={run.processedProducts} max={Math.max(run.totalProducts, 1)} /></div>) : <p>No indexing runs yet.</p>}</div></section>
    <section className="panel ranking-panel"><div className="panel-heading"><div><p className="kicker">RANKING</p><h2>Balanced preset</h2></div><button disabled={!ranking || pending} onClick={() => startTransition(() => void saveRanking())}>Save weights</button></div>
      {ranking ? <div className="sliders">{Object.entries(ranking).filter(([key]) => key !== "version").map(([key, value]) => <label key={key}><span>{key.replace(/([A-Z])/g, " $1")}</span><input type="range" min="0" max="1" step="0.05" value={value} onChange={(event) => setRanking({ ...ranking, [key]: Number(event.target.value) } as RankingConfig)} /><output>{value.toFixed(2)}</output></label>)}</div> : <p>Loading ranking configuration…</p>}</section>
    <section className="panel eval-panel"><div className="panel-heading"><div><p className="kicker">RELEVANCE</p><h2>Judgment workspace</h2></div><span className="status-dot muted">nDCG@10</span></div><p>Create evaluation queries through the API, attach deliberate local image fixtures, and grade Brand+Series groups from 0–2. Reports compare keyword, hybrid, visual, and fused modes without enforcing a release gate.</p><a href={`${API.replace(/\/v1$/, "")}/docs`} target="_blank" rel="noreferrer">Open evaluator API →</a></section>
  </div>;
}
